// USERS
export const CREATE_USERS = "CREATE_USERS"
export const CREATE_USERS_RED = "CREATE_USERS_RED"
export const GET_USERS = "GET_USERS"
export const GET_USERS_RED = "GET_USERS_RED"
export const UPDATE_USERS = "UPDATE_USERS"
export const UPDATE_USERS_RED = "UPDATE_USERS_RED"
export const DELETE_USERS = "DELETE_USERS"
export const DELETE_USERS_RED = "DELETE_USERS_RED"

// JOBS
export const CREATE_JOBS = "CREATE_JOBS"
export const CREATE_JOBS_RED = "CREATE_JOBS_RED"
export const GET_JOBS = "GET_JOBS"
export const GET_JOBS_RED = "GET_JOBS_RED"
export const UPDATE_JOBS = "UPDATE_JOBS"
export const UPDATE_JOBS_RED = "UPDATE_JOBS_RED"
export const DELETE_JOBS = "DELETE_JOBS"
export const DELETE_JOBS_RED = "DELETE_JOBS_RED"

// REPORTS
export const CREATE_REPORTS = "CREATE_REPORTS"
export const CREATE_REPORTS_RED = "CREATE_REPORTS_RED"
export const GET_REPORTS = "GET_REPORTS"
export const GET_REPORTS_RED = "GET_REPORTS_RED"
export const UPDATE_REPORTS = "UPDATE_REPORTS"
export const UPDATE_REPORTS_RED = "UPDATE_REPORTS_RED"
export const DELETE_REPORTS = "DELETE_REPORTS"
export const DELETE_REPORTS_RED = "DELETE_REPORTS_RED"

// APPLICATIONS
export const CREATE_APPLICATIONS = "CREATE_APPLICATIONS"
export const CREATE_APPLICATIONS_RED = "CREATE_APPLICATIONS_RED"
export const GET_APPLICATIONS = "GET_APPLICATIONS"
export const GET_APPLICATIONS_RED = "GET_APPLICATIONS_RED"
export const UPDATE_APPLICATIONS = "UPDATE_APPLICATIONS"
export const UPDATE_APPLICATIONS_RED = "UPDATE_APPLICATIONS_RED"
export const DELETE_APPLICATIONS = "DELETE_APPLICATIONS"
export const DELETE_APPLICATIONS_RED = "DELETE_APPLICATIONS_RED"

// COMPANIES
export const CREATE_COMPANIES = "CREATE_COMPANIES"
export const CREATE_COMPANIES_RED = "CREATE_COMPANIES_RED"
export const GET_COMPANIES = "GET_COMPANIES"
export const GET_COMPANIES_RED = "GET_COMPANIES_RED"
export const UPDATE_COMPANIES = "UPDATE_COMPANIES"
export const UPDATE_COMPANIES_RED = "UPDATE_COMPANIES_RED"
export const DELETE_COMPANIES = "DELETE_COMPANIES"
export const DELETE_COMPANIES_RED = "DELETE_COMPANIES_RED"

// SETTINGS
export const CREATE_SETTINGS = "CREATE_SETTINGS"
export const CREATE_SETTINGS_RED = "CREATE_SETTINGS_RED"
export const GET_SETTINGS = "GET_SETTINGS"
export const GET_SETTINGS_RED = "GET_SETTINGS_RED"
export const UPDATE_SETTINGS = "UPDATE_SETTINGS"
export const UPDATE_SETTINGS_RED = "UPDATE_SETTINGS_RED"
export const DELETE_SETTINGS = "DELETE_SETTINGS"
export const DELETE_SETTINGS_RED = "DELETE_SETTINGS_RED"

// NOTIFICATIONS
export const CREATE_NOTIFICATIONS = "CREATE_NOTIFICATIONS"
export const CREATE_NOTIFICATIONS_RED = "CREATE_NOTIFICATIONS_RED"
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS"
export const GET_NOTIFICATIONS_RED = "GET_NOTIFICATIONS_RED"
export const UPDATE_NOTIFICATIONS = "UPDATE_NOTIFICATIONS"
export const UPDATE_NOTIFICATIONS_RED = "UPDATE_NOTIFICATIONS_RED"
export const DELETE_NOTIFICATIONS = "DELETE_NOTIFICATIONS"
export const DELETE_NOTIFICATIONS_RED = "DELETE_NOTIFICATIONS_RED"

export const MARK_READ = "MARK_READ";
export const MARK_UNREAD = "MARK_UNREAD"; // optional

export const MARK_READ_RED = "MARK_READ_RED";
export const MARK_UNREAD_RED = "MARK_UNREAD_RED";

// AUDITLOGS
export const CREATE_AUDITLOGS = "CREATE_AUDITLOGS"
export const CREATE_AUDITLOGS_RED = "CREATE_AUDITLOGS_RED"
export const GET_AUDITLOGS = "GET_AUDITLOGS"
export const GET_AUDITLOGS_RED = "GET_AUDITLOGS_RED"
export const UPDATE_AUDITLOGS = "UPDATE_AUDITLOGS"
export const UPDATE_AUDITLOGS_RED = "UPDATE_AUDITLOGS_RED"
export const DELETE_AUDITLOGS = "DELETE_AUDITLOGS"
export const DELETE_AUDITLOGS_RED = "DELETE_AUDITLOGS_RED"